//View all
export const POSTS_LIST_REQUEST = 'POSTS_LIST_REQUEST'
export const POSTS_LIST_SUCCESS = 'POSTS_LIST_SUCCESS'
export const POSTS_LIST_FAIL = 'POSTS_LIST_FAIL'

//Get by id
export const POSTS_DETAILS_REQUEST = 'POSTS_DETAILS_REQUEST'
export const POSTS_DETAILS_SUCCESS = 'POSTS_DETAILS_SUCCESS'
export const POSTS_DETAILS_FAIL = 'POSTS_DETAILS_FAIL'

//Delete by id
export const POSTS_DELETE_REQUEST = 'POSTS_DELETE_REQUEST'
export const POSTS_DELETE_SUCCESS = 'POSTS_DELETE_SUCCESS'
export const POSTS_DELETE_FAIL = 'POSTS_DELETE_FAIL'

//add post
export const POSTS_CREATE_REQUEST = 'POSTS_CREATE_REQUEST'
export const POSTS_CREATE_SUCCESS = 'POSTS_CREATE_SUCCESS'
export const POSTS_CREATE_FAIL = 'POSTS_CREATE_FAIL'
export const POSTS_CREATE_RESET = 'POSTS_CREATE_RESET'
